### Student_book create
POST localhost:8080/student-book
Content-Type: application/json

{
  "studentId": "e4e34cb7-957e-4304-abf2-ef2d4d7d8171",
  "bookId": "9fdb9147-395f-4340-ab8e-2316eb57c6b8"
}

### Student_Book update
PUT localhost:8080/student-book/
Content-Type: application/json

{
  "studentId": "e4e34cb7-957e-4304-abf2-ef2d4d7d8171",
  "bookId": "9fdb9147-395f-4340-ab8e-2316eb57c6b8"
}

### Student_Book list
GET localhost:8080/student-book

### Student_Book byId
GET localhost:8080/student-book/9c2899ff-81b5-4410-9cd7-fe2aea40b4b6
